// The desk module catalogue the model sees (desk-row-grounding spec §D).
// deskCatalog.json is generated by `npx vite-node scripts/build-desk-catalog.mjs`
// from src/desks/catalog.js and the desk feed pipeline; src/lib/deskCatalog.test.js
// fails when it is stale. This file only reads it.

import catalog from './deskCatalog.json' with { type: 'json' };

export interface CatalogEntry {
  tier: string; // desk tab id: global | national | state | law | economics | carbon | sports | entertainment
  feature: string; // module name, exactly as the desk and the tool expect it
  bucket: string;
  pack: string | null;
  rows: number; // rows the desk showed when the catalogue was generated
  note: string | null;
}

export const DESK_TIERS = ['global', 'national', 'state', 'law', 'economics', 'carbon', 'sports', 'entertainment'] as const;

export const DESK_CATALOG: readonly CatalogEntry[] = (catalog as { entries: CatalogEntry[] }).entries;

export function normaliseName(s: unknown): string {
  return String(s ?? '')
    .toLowerCase()
    .replace(/[–—−]/g, '-')
    .replace(/&amp;/g, '&')
    .replace(/\s+/g, ' ')
    .trim();
}

/** The catalogue entry for a module named by the model: exact, then case-, dash- and space-insensitive, within the tier. */
export function resolveFeature(tier: string, name: string): CatalogEntry | null {
  const inTier = DESK_CATALOG.filter((e) => e.tier === tier);
  const want = String(name ?? '').trim();
  if (!want) return null;
  return inTier.find((e) => e.feature === want) ?? inTier.find((e) => normaliseName(e.feature) === normaliseName(want)) ?? null;
}

function longLine(e: CatalogEntry): string {
  const rows = e.rows > 0 ? `${e.rows.toLocaleString('en-IN')} rows` : 'no rows loaded';
  return `- ${e.feature} (${e.bucket}) — ${rows}${e.note ? ` · ${e.note}` : ''}`;
}

function shortLine(tier: string): string {
  return `${tier}: ${DESK_CATALOG.filter((e) => e.tier === tier).map((e) => e.feature).join(', ')}`;
}

/**
 * The prompt block: the current desk's modules one per line with their row
 * counts and notes, the other desks by name only. Without a tier, every desk
 * in the short form.
 */
export function deskCatalogBlock(tier?: string): string {
  const tiers = DESK_TIERS.filter((t) => DESK_CATALOG.some((e) => e.tier === t));
  if (tier && tiers.includes(tier as typeof DESK_TIERS[number])) {
    const here = DESK_CATALOG.filter((e) => e.tier === tier);
    const others = tiers.filter((t) => t !== tier);
    return [
      `Modules on the ${tier} desk (name them exactly in search_desk_rows):`,
      ...here.map(longLine),
      'Other desks:',
      ...others.map(shortLine),
    ].join('\n');
  }
  return ['Desk modules (name them exactly in search_desk_rows):', ...tiers.map(shortLine)].join('\n');
}
