import { useId, useRef, useState } from 'react';
import { ArrowRight, ArrowUpRight, Database, FileText, Network, Newspaper, Pause, Play, Users } from 'lucide-react';
import { DESK_IMAGES, DESK_IMAGE_CREDITS } from './deskImages.js';
import { formatCount, moduleAvailability, sourceDate, summarizeModules } from './deskPresentation.js';
import V6Photo from './V6Photo.jsx';
import V6Dialog from './V6Dialog.jsx';
import useDeskLandingMotion from './useDeskLandingMotion.js';
import './deskLandingV6.css';

const hasSource = summary => Boolean(summary && (summary.sources?.some(source => safeUrl(source.url)) || (!['error', 'unavailable'].includes(summary.availability) && ['stored', 'feed-backed', 'curated'].includes(summary.sourceMode))));
export const groupsWithSources = (groups, summaries) => groups.filter(group => group.modules.some(module => hasSource(summaries[module.feature])));
const safeUrl = value => { try { const url = new URL(value); return /^https?:$/.test(url.protocol) ? url.href : null; } catch { return null; } };
const ModuleIcon = ({ module, summary }) => {
  const Icon = module.feature.includes('Graph') ? Network : summary?.sourceMode === 'feed-backed' ? Newspaper : /Candidate|Profiles|Heads/.test(module.feature) ? Users : FileText;
  return <Icon aria-hidden="true" />;
};
const Count = ({ value }) => <span data-v6-count={Number.isInteger(value) ? value : undefined}>{formatCount(value)}</span>;
const moduleNote = (module, summary) => `${formatCount(summary?.count)} ${summary?.unit || 'records'} · ${moduleAvailability(module, summary)}`;

export function ModuleDetail({ module, summary, onOpen, retry, titleId }) {
  const sources = (summary?.sources || []).filter(source => safeUrl(source.url));
  return <div className="detail-inner"><div className="eyebrow">MODULE COVERAGE</div><h2 id={titleId}>{module.title}</h2><span className="status">{moduleAvailability(module, summary)}</span><div className="detail-count"><b>{formatCount(summary?.count)}</b><span>{summary?.unit || 'records'}</span></div><p className="detail-note">{summary?.limitations || 'Source coverage is not available yet.'}</p><h3>FIELDS &amp; COVERAGE</h3><div className="field-chips">{summary?.columns?.length ? summary.columns.map(column => <span key={column.key}>{column.label}</span>) : <span>No populated fields reported</span>}</div><h3>ABOUT THE DATA</h3><p>{sourceDate(summary?.asOf)}{summary?.period ? ` · ${summary.period}` : ''}</p>{summary?.resourceKey && summary.resourceKey !== module.feature && <p>Uses the shared {summary.resourceKey} register. Counted once in desk totals.</p>}<div className="field-chips source-links">{sources.map(source => <a href={safeUrl(source.url)} target="_blank" rel="noopener noreferrer" key={source.url}>{source.name}<ArrowUpRight aria-hidden="true" /></a>)}</div>{!sources.length && <p>Source links are not supplied in this summary.</p>}<div className="detail-action"><p>Open the existing workspace to explore its records.</p><div>{summary?.availability === 'error' && retry && <button onClick={() => retry(module.feature)}>Retry summary</button>}<button className="primary" onClick={() => onOpen(module.feature)}>Open in Terminal <ArrowUpRight aria-hidden="true" /></button></div></div></div>;
}
export function DataBreakdown({ title, items, stages = [], asOf, titleId }) {
  const max = Math.max(1, ...items.map(item => item.count));
  return <div className="detail-inner"><div className="eyebrow">COVERAGE OVERVIEW</div><h2 id={titleId}>{title}</h2><p>{title === 'Bills by sector' ? 'Classification from the prepared register. Missing classifications remain visible.' : 'Known counts grouped by research sector. Missing totals are not treated as zero; see each module for its units.'}</p><div className="breakdown-chart">{items.length ? items.map(item => <div className="breakdown-row" key={item.label}><span>{item.label}</span><b>{formatCount(item.count)}</b><div><i style={{ width: `${item.count / max * 100}%` }} /></div></div>) : <p>Distribution is not available yet.</p>}</div>{stages.length > 0 && <><h3>BILL STAGES</h3><div className="field-chips">{stages.map(stage => <span key={stage.label}>{stage.label} <b>{formatCount(stage.count)}</b></span>)}</div></>}<p className="detail-note">{sourceDate(asOf)}. See each module for its source and coverage limitations.</p></div>;
}
function Insight({ items, count, onOpen, national }) {
  const [hover, setHover] = useState(null);
  const max = Math.max(1, ...items.map(item => item.count));
  return <aside className={`hero-insight ${hover ? 'chart-active' : ''}`} aria-label="Desk data highlight"><div className="insight-top">{national ? 'THE LEGISLATIVE LANDSCAPE' : 'DESK COVERAGE'}<i /></div><div className="insight-number"><b><Count value={count} /></b><span>{national ? 'bills on record' : 'counted records'}</span></div><div className="mini-bars" role="group" aria-label={national ? 'Bills by sector' : 'Known counts by sector'}>{items.map((item, index) => <button key={item.label} className="mini-bar" style={{ '--height': `${Math.max(5, item.count / max * 100)}%`, '--i': index }} aria-label={`${item.label}: ${formatCount(item.count)} records`} onPointerEnter={() => setHover(item)} onPointerLeave={() => setHover(null)} onFocus={() => setHover(item)} onBlur={() => setHover(null)} onClick={onOpen}><i /></button>)}</div><div className="insight-foot"><span>{hover ? `${hover.label} · ${formatCount(hover.count)}` : items.length ? 'KNOWN COUNTS BY SECTOR' : 'Distribution unavailable'}</span><button onClick={onOpen}>View data <ArrowUpRight aria-hidden="true" /></button></div></aside>;
}

export default function DeskLandingFrame({ presentation, summaries = {}, onFeature, retry, lang = 'en', toolbar, metrics }) {
  const [selected, setSelected] = useState(presentation.groups[0]?.id);
  const [filter, setFilter] = useState('all');
  const [detail, setDetail] = useState(null);
  const explorer = useRef(null);
  const id = useId();
  const modules = presentation.groups.flatMap(group => group.modules);
  const aggregate = summarizeModules(modules, summaries);
  const motion = useDeskLandingMotion(Object.values(summaries).map(summary => summary.count).join(','));
  const groups = filter === 'sources' ? groupsWithSources(presentation.groups, summaries) : presentation.groups;
  const group = groups.find(item => item.id === selected) || groups[0];
  const national = presentation.id === 'national';
  const bills = national ? summaries['Bill Passage Probability Index'] : null;
  const items = national ? bills?.sectors || [] : presentation.groups.map(item => ({ label: item.short, count: summarizeModules(item.modules, summaries).count })).filter(item => item.count != null);
  const defaultMetrics = [{ label: 'Counted records', value: aggregate.count, note: 'Known counts; shared resources counted once' }, { label: 'Modules', value: modules.length, note: 'Full section catalogue' }, { label: 'Sectors', value: presentation.groups.length, note: 'Areas to explore' }];
  const openFeature = feature => { setDetail(null); onFeature(feature); };
  return <div ref={motion.ref} className={`desk-v6 ${motion.paused ? 'motion-paused' : ''} ${!['national', 'global', 'law'].includes(presentation.id) ? 'expanded-desk' : ''}`} data-desk={presentation.id} lang={lang}>
    <div className="v6-main"><div className="crumb"><span>INTELLIGENCE DESKS</span><span>/</span><b>{presentation.name}</b><span className="snapshot"><i />{aggregate.pending ? 'Loading summaries' : 'Summary requests complete'}</span>{toolbar}</div>
      <section className="hero" aria-labelledby={`${id}-title`}><div className="hero-photo" aria-hidden="true"><img src={DESK_IMAGES[presentation.image] || DESK_IMAGES[`${presentation.image}.jpg`]} alt="" fetchPriority="high" /></div><div className="hero-copy"><div className="eyebrow"><span className="small-line" />THE {presentation.name.toUpperCase()} DESK</div><h1 id={`${id}-title`}>{presentation.title[0]}<br /><span>{presentation.title[1]}</span></h1><p>{presentation.description}</p><div className="hero-bottom"><button className="primary" onClick={() => explorer.current?.scrollIntoView({ behavior: motion.paused ? 'instant' : 'smooth', block: 'nearest' })}>Explore the desk <ArrowRight aria-hidden="true" /></button><span className="hero-meta">{presentation.groups.length} sectors · {modules.length} modules · one perspective</span></div></div><Insight items={items} count={national ? bills?.count : aggregate.count} national={national} onOpen={() => setDetail('data')} /><span className="photo-label">{presentation.imageLabel}</span></section>
      <section className="stats" aria-label="Desk statistics">{(metrics || defaultMetrics).map(metric => <div className="stat" key={metric.label}><div className="stat-label"><Database aria-hidden="true" />{metric.label}</div><div className="stat-value"><Count value={metric.value} /></div><div className="stat-note">{metric.note}</div></div>)}</section>
      <div className="section-heading"><div><h2>{presentation.heading}</h2><span>Choose a sector. Explore its records.</span></div><div className="sector-controls"><span>{groups.length} sectors to explore</span><div className="segmented" aria-label="Sector coverage filter"><button aria-pressed={filter === 'all'} onClick={() => setFilter('all')}>All</button><button aria-pressed={filter === 'sources'} onClick={() => setFilter('sources')}><i />With sources</button></div></div></div>
      <section className="sector-grid" aria-label="Research sectors">{groups.map(item => { const totals = summarizeModules(item.modules, summaries); const index = presentation.groups.indexOf(item); const modes = [...new Set(item.modules.map(module => summaries[module.feature]?.sourceMode).filter(mode => mode && mode !== 'unknown'))]; return <button className="sector-card" key={item.id} style={{ '--i': index }} aria-pressed={group?.id === item.id} aria-controls={`${id}-modules`} aria-label={`Explore ${item.name}: ${item.modules.length} modules`} onClick={() => { setSelected(item.id); if (window.innerWidth <= 850) explorer.current?.scrollIntoView({ behavior: motion.paused ? 'instant' : 'smooth', block: 'nearest' }); }}><div className={`card-picture picture-${item.image}`} data-image={item.image}><V6Photo name={item.image} /><span className="card-number">{String(index + 1).padStart(2, '0')}</span><span className="card-count">{item.modules.length} modules</span></div><div className="card-body"><div className="card-title-row"><h3>{item.title[0]}<br />{item.title[1]}</h3><ArrowUpRight aria-hidden="true" /></div><p className="card-desc">{item.cardDescription || item.description}</p><div className="card-bottom"><span className="card-total">{formatCount(totals.count)}{totals.pending && totals.count != null ? '+' : ''}<small>records</small></span><span className="status">{modes.length > 1 ? 'Mixed sources' : modes[0] === 'stored' ? 'Stored register' : modes[0] === 'feed-backed' ? 'News & feeds' : modes[0] === 'curated' ? 'Curated records' : totals.pending ? 'Loading' : 'Coverage unavailable'}</span></div></div></button>; })}</section>
      <section ref={explorer} className={`explorer ${group?.id === 'economy' ? 'budget-sector' : ''}`} aria-labelledby={`${id}-explorer`}><div className="explorer-heading"><div><span className="eyebrow">INSIDE THIS SECTOR</span><h2 id={`${id}-explorer`}>{group?.name || 'No sectors with source coverage'}</h2><p>{group?.description || 'Select All to browse the full catalogue.'}</p></div><span className="explorer-badge">{group?.modules.length || 0} modules · {group?.modules.filter(module => hasSource(summaries[module.feature])).length || 0} with sources</span></div><div key={group?.id} className="module-list refresh" id={`${id}-modules`} tabIndex={0} aria-label="Modules in the selected sector">{group?.modules.map((module, index) => <button className="module-item" key={module.feature} style={{ '--i': index }} onClick={() => setDetail(module)} aria-label={`${module.title}: ${moduleNote(module, summaries[module.feature])}`}><span className="module-icon"><ModuleIcon module={module} summary={summaries[module.feature]} /></span><span className="module-copy"><b>{module.title}</b><span>{moduleNote(module, summaries[module.feature])}</span></span><ArrowRight aria-hidden="true" /></button>)}</div></section>
      <footer><span>Counts reflect available source summaries; coverage varies.</span><div><a href={DESK_IMAGE_CREDITS} target="_blank" rel="noopener noreferrer">Image credits</a><button onClick={motion.toggle} disabled={motion.reduced} aria-pressed={motion.paused}>{motion.paused ? <Play aria-hidden="true" /> : <Pause aria-hidden="true" />}{motion.reduced ? 'Reduced motion' : motion.paused ? 'Resume motion' : 'Pause motion'}</button></div></footer>
    </div>{detail && <V6Dialog titleId={`${id}-dialog`} onClose={() => setDetail(null)}>{detail === 'data' ? <DataBreakdown title={national ? 'Bills by sector' : 'Coverage at a glance'} items={items} stages={bills?.stages} asOf={bills?.asOf} titleId={`${id}-dialog`} /> : <ModuleDetail module={detail} summary={summaries[detail.feature]} retry={retry} onOpen={openFeature} titleId={`${id}-dialog`} />}</V6Dialog>}
  </div>;
}
